"use client";

import { Card } from "@/components/ui/card";
import { PaperChart } from "@/components/paper-chart";
import { getApiUrl } from "@/lib/api";
import { useCallback, useEffect, useMemo, useState } from "react";

type AnyRow = Record<string, any>;
type ChartPoint = { timestamp: string; [key: string]: string | number };
const money = (value: unknown) => Number(value ?? 0).toLocaleString(undefined, { maximumFractionDigits: 2 });

export default function PaperPage() {
  const [status, setStatus] = useState<AnyRow>({});
  const [account, setAccount] = useState<AnyRow>({});
  const [positions, setPositions] = useState<AnyRow[]>([]);
  const [trades, setTrades] = useState<AnyRow[]>([]);
  const [performance, setPerformance] = useState<AnyRow>({});
  const [curve, setCurve] = useState<ChartPoint[]>([]);
  const [health, setHealth] = useState<AnyRow>({});
  const [message, setMessage] = useState("");
  const [resetArmed, setResetArmed] = useState(false);
  const load = useCallback(async () => {
    try {
      const api = getApiUrl();
      const [s, a, p, t, perf, eq, h] = await Promise.all(["status", "account", "positions?open_only=true", "trades", "performance", "equity", "health"].map((path) => fetch(`${api}/paper/${path}`, { cache: "no-store" }).then((r) => r.json())));
      setStatus(s); setAccount(a); setPositions(p.items ?? []); setTrades(t.items ?? []); setPerformance(perf); setCurve((eq.items ?? []) as ChartPoint[]); setHealth(h); setMessage("");
    } catch (error) { setMessage(error instanceof Error ? error.message : "Paper API unavailable"); }
  }, []);
  useEffect(() => { load(); const timer = setInterval(load, 5000); return () => clearInterval(timer); }, [load]);
  const action = async (path: string) => { const api = getApiUrl(); const response = await fetch(`${api}/paper/${path}`, { method: "POST" }); const body = await response.json(); setMessage(response.ok ? `${path.split("?")[0]} completed` : body.detail ?? "Request failed"); await load(); };
  const metrics = performance.metrics ?? {};
  const daily = useMemo(() => {
    const values = new Map<string, number>();
    trades.forEach((trade) => { const day = String(trade.timestamp).slice(0, 10); values.set(day, (values.get(day) ?? 0) + Number(trade.net_pnl)); });
    return [...values].map(([timestamp, daily_pnl]) => ({ timestamp: `${timestamp}T00:00:00Z`, daily_pnl }));
  }, [trades]);
  const cards = [["Initial equity", account.initial_equity], ["Current equity", account.equity], ["Today’s P&L", account.daily_pnl], ["Total P&L", metrics.net_pnl], ["Return %", metrics.total_return_percent], ["Win rate %", metrics.win_rate], ["Profit factor", metrics.profit_factor ?? "—"], ["Expectancy", metrics.expectancy], ["Max drawdown", metrics.maximum_drawdown], ["Open positions", metrics.open_positions], ["Total trades", metrics.trades]];
  return <main className="mx-auto max-w-7xl p-4 sm:p-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-300">Paper Trading</p><h1 className="mt-1 text-3xl font-semibold">Live-market simulation</h1><p className="mt-2 text-sm text-slate-400">Public CoinDCX data · production strategy and risk logic · simulated execution only</p></div><div className="rounded-xl border border-amber-400/40 bg-amber-400/10 px-4 py-3 text-center"><p className="font-bold text-amber-300">NO REAL ORDERS</p><p className="text-xs uppercase text-slate-400">{status.engine_status ?? "loading"}</p></div></header>
    <div className="mt-5 flex flex-wrap gap-2"><button onClick={() => action("start")} className="rounded-lg bg-amber-400 px-4 py-2 text-sm font-bold text-slate-950">Start paper session</button><button onClick={() => action("stop")} className="rounded-lg border border-slate-600 px-4 py-2 text-sm">Stop</button>{!resetArmed ? <button onClick={() => setResetArmed(true)} className="rounded-lg border border-rose-500/50 px-4 py-2 text-sm text-rose-300">Review reset</button> : <div className="flex items-center gap-2 rounded-lg border border-rose-500/40 p-2 text-xs"><span>Equity {money(account.equity)} · {positions.length} open · {trades.length} trades</span><button onClick={() => action("reset?confirmation=RESET%20PAPER%20TRADING")} className="rounded bg-rose-500 px-3 py-1 font-bold">Confirm reset</button><button onClick={() => setResetArmed(false)}>Cancel</button></div>}</div>
    {message && <p className="mt-3 rounded-lg border border-slate-700 p-3 text-sm text-slate-300">{message}</p>}
    {(status.trading_blocked || health.trading_blocked) && <div className="mt-4 rounded-xl border border-rose-500/50 bg-rose-500/10 p-4"><p className="font-bold text-rose-300">PAPER TRADING BLOCKED</p><p className="text-sm text-slate-300">{status.block_reason || health.block_reason || "Phase 7 risk lock"}</p></div>}
    <section className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">{cards.map(([label, value]) => <Card key={String(label)}><p className="text-xs uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{typeof value === "number" ? money(value) : String(value ?? "—")}</p></Card>)}</section>
    <section className="mt-5 grid gap-3 md:grid-cols-3"><Card><p className="text-xs uppercase text-slate-500">Current opportunities</p><p className="mt-2 text-2xl font-semibold">{status.live_feed?.current_opportunities ?? 0}</p></Card><Card><p className="text-xs uppercase text-slate-500">Current setups</p><p className="mt-2 text-2xl font-semibold">{status.live_feed?.current_setups ?? 0}</p></Card><Card><p className="text-xs uppercase text-slate-500">Risk decisions</p><p className="mt-2 text-2xl font-semibold">{status.live_feed?.risk_decisions ?? 0}</p></Card></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-2"><Card><h2 className="font-semibold">Equity curve</h2><PaperChart points={curve} field="equity" /></Card><Card><h2 className="font-semibold">Drawdown</h2><PaperChart points={curve} field="drawdown" color="#fb7185" /></Card><Card><h2 className="font-semibold">Cumulative P&L</h2><PaperChart points={curve} field="cumulative_pnl" color="#a78bfa" /></Card><Card><h2 className="font-semibold">Daily P&L</h2>{daily.length ? <PaperChart points={daily} field="daily_pnl" color="#fbbf24" /> : <p className="mt-8 text-sm text-slate-500">No completed paper trades yet.</p>}</Card></section>
    <section className="mt-5"><h2 className="mb-3 text-lg font-semibold">Active positions</h2><div className="grid gap-3 lg:grid-cols-2">{positions.length ? positions.map((p) => <Card key={p.position_id}><div className="flex justify-between"><div><p className="font-semibold">{p.symbol} · {String(p.direction).toUpperCase()}</p><p className="text-xs text-slate-400">{p.strategy} · opportunity {p.opportunity_score} · setup {p.setup_score}</p></div><button onClick={() => action(`close/${p.position_id}`)} className="rounded border border-amber-500/40 px-3 text-xs text-amber-300">Paper close</button></div><div className="mt-4 grid grid-cols-3 gap-3 text-sm"><span>Entry<br/><b>{money(p.entry_price)}</b></span><span>Current<br/><b>{money(p.current_price)}</b></span><span>Unrealized<br/><b>{money(p.unrealized_pnl)}</b></span><span>Stop<br/><b>{money(p.stop_price)}</b></span><span>Target<br/><b>{money(p.target_price)}</b></span><span>Current R<br/><b>{money(p.current_r)}</b></span><span>Quantity<br/><b>{money(p.quantity)}</b></span><span>Notional<br/><b>{money(p.notional)}</b></span><span>Duration<br/><b>{money(p.duration_minutes)}m</b></span></div></Card>) : <Card><p className="text-sm text-slate-500">No open simulated positions.</p></Card>}</div></section>
    <section className="mt-5 grid gap-4 lg:grid-cols-3"><Card><h2 className="font-semibold">Strategy health</h2><p className="mt-2 text-lg uppercase text-amber-300">{performance.strategy_health?.state ?? "—"}</p>{(performance.strategy_health?.warnings ?? []).map((w: string) => <p className="mt-2 text-sm text-slate-400" key={w}>{w}</p>)}</Card><Card><h2 className="font-semibold">Backtest vs paper</h2><p className="mt-2 text-sm text-slate-400">{performance.backtest_comparison?.available ? "Latest completed backtest baseline loaded. Deviations are descriptive, not an automatic trading lock." : performance.backtest_comparison?.reason ?? "No baseline"}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs">{Object.entries(performance.backtest_comparison?.deviations ?? {}).slice(0, 6).map(([key, value]) => <span key={key}>{key}<br/><b>{value == null ? "—" : money(value)}</b></span>)}</div></Card><Card><h2 className="font-semibold">R distribution</h2><div className="mt-3 space-y-2">{Object.entries(metrics.r_distribution ?? {}).length ? Object.entries(metrics.r_distribution).map(([bucket, count]) => <div key={bucket} className="flex items-center justify-between text-sm"><span className="text-slate-400">{bucket}</span><b>{String(count)}</b></div>) : <p className="text-sm text-slate-500">No completed trades.</p>}</div></Card></section>
    <section className="mt-5"><h2 className="mb-3 text-lg font-semibold">Live setup feed</h2><Card>{(status.live_feed?.recent_activity ?? []).length ? status.live_feed.recent_activity.map((event: AnyRow, index: number) => <div className="flex gap-3 border-b border-slate-800 py-2 text-sm last:border-0" key={`${event.timestamp}-${index}`}><time className="text-slate-500">{new Date(event.timestamp).toLocaleTimeString()}</time><b>{event.symbol ?? "SYSTEM"}</b><span className="text-slate-300">{event.event_type}</span></div>) : <p className="text-sm text-slate-500">No paper setup or execution events in this session.</p>}</Card></section>
    <section className="mt-5"><h2 className="mb-3 text-lg font-semibold">Paper trade activity</h2><Card className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="pb-3">Time</th><th>Symbol</th><th>Strategy</th><th>Direction</th><th>Exit</th><th>Net P&L</th><th>R</th><th>Fees</th></tr></thead><tbody>{trades.map((t) => <tr key={t.trade_id} className="border-t border-slate-800"><td className="py-3">{new Date(t.timestamp).toLocaleString()}</td><td>{t.symbol}</td><td>{t.strategy}</td><td>{String(t.direction).toUpperCase()}</td><td>{t.exit_reason}</td><td>{money(t.net_pnl)}</td><td>{money(t.r_multiple)}</td><td>{money(t.fees)}</td></tr>)}</tbody></table>{!trades.length && <p className="py-6 text-sm text-slate-500">No paper activity yet.</p>}</Card></section>
  </main>;
}
